#!/usr/bin/env python3
import argparse,json,re
from pathlib import Path
from datetime import datetime,UTC
p=argparse.ArgumentParser(description="AI_CodeGenerator real runner");p.add_argument("--task",required=True);p.add_argument("--context",default="");p.add_argument("--constraints",default="");a=p.parse_args()
name=re.sub(r"[^a-z0-9]+","-",a.task.strip().lower()).strip("-") or "fastapi-app"
root=Path("/home/jason/.openclaw/workspace/generated")/name;app=root/"app";app.mkdir(parents=True,exist_ok=True)
(root/"requirements.txt").write_text("fastapi==0.115.0\nuvicorn==0.30.6\n",encoding="utf-8")
(root/"README.md").write_text(f"# {name}\n\nGenerated by AI_CodeGenerator.\n",encoding="utf-8")
(app/"__init__.py").write_text("",encoding="utf-8")
(app/"main.py").write_text('from fastapi import FastAPI\napp=FastAPI(title="Generated FastAPI App")\n@app.get("/")\ndef read_root():\n return {"message":"Hello from generated FastAPI app"}\n',encoding="utf-8")
print(json.dumps({"skill":"AI_CodeGenerator","status":"ok","task":a.task,"project_path":str(root),"timestamp":datetime.now(UTC).isoformat().replace("+00:00","Z"),"summary":"FastAPI project scaffold generated."},ensure_ascii=False,indent=2))
